import { Raleway as RalewayFont } from "next/font/google"
import "./globals.css"
import Header from "./_components/Header"

const raleway = RalewayFont({ subsets: ["latin"], weight: "500" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}